Repository code-423n4/code423n4.com, pull requests merged in 2022-07, with the labels that each got.

#2570 Update warden 0xKitsune
  _data/handles/0xKitsune.json
Labels: re-registration

#2571 Update warden Amithuddar
  _data/handles/Amithuddar.json
Labels: re-registration

#2572 Update warden GalloDaSballo
  _data/handles/GalloDaSballo.json
Labels: re-registration

#2576 Register warden cheb
  _data/handles/avatars/cheb.png
  _data/handles/cheb.json
Labels: app-warden

#2547 Register warden gerdusx
  _data/handles/gerdusx.json
Labels: app-warden

#2568 Register warden jpserrat
  _data/handles/avatars/jpserrat.png
  _data/handles/jpserrat.json
Labels: app-warden

#2574 Update warden ballx
  _data/handles/ballx.json
Labels: re-registration

#2575 Update warden sseefried
  _data/handles/sseefried.json
Labels: re-registration

#2552 Register warden apajaresaguilera
  _data/handles/apajaresaguilera.json
  _data/handles/avatars/apajaresaguilera.jpeg
Labels: app-warden

#2528 Register warden shando
  _data/handles/avatars/shando.png
  _data/handles/shando.json
Labels: app-warden

#2579 Update warden SamusElderg
  _data/handles/SamusElderg.json
  _data/handles/avatars/SamusElderg.png
Labels: re-registration

#2580 Update warden zzzitron
  _data/handles/zzzitron.json
Labels: re-registration

#2582 Update warden wuestholz
  _data/handles/wuestholz.json
Labels: re-registration

#2587 Update warden rishabh
  _data/handles/rishabh.json
Labels: re-registration

#2589 Update warden Tutturu
  _data/handles/Tutturu.json
Labels: re-registration

#2598 Update warden Waze
  _data/handles/Waze.json
Labels: re-registration

#2599 Update warden Limbooo
  _data/handles/Limbooo.json
Labels: re-registration

#2600 Update warden Critical
  _data/handles/Critical.json
Labels: re-registration

#2601 Update warden ladboy233
  _data/handles/ladboy233.json
Labels: re-registration

#2594 1666 support easier stealing of contest art
  src/styles/contest.css
  src/templates/ContestLayout.js
Labels: ready for review

#2610 Update warden AmitN
  _data/handles/AmitN.json
Labels: re-registration

#2616 Update warden hake
  _data/handles/hake.json
Labels: re-registration

#2615 Update warden aysha
  _data/handles/aysha.json
Labels: re-registration

#2618 Update warden JohnSmith
  _data/handles/JohnSmith.json
Labels: re-registration

#2620 Update warden 0xNazgul
  _data/handles/0xNazgul.json
Labels: re-registration

#2623 Update warden asutorufos
  _data/handles/asutorufos.json
Labels: re-registration

#2625 Update warden Haruxe
  _data/handles/Haruxe.json
Labels: re-registration

#2583 Register warden chroma
  _data/handles/chroma.json
Labels: app-warden

#2585 Register warden Junnon
  _data/handles/Junnon.json
Labels: app-warden

#2590 Register warden ReyAdmirado
  _data/handles/ReyAdmirado.json
Labels: app-warden

#2592 Register warden 0xHarry
  _data/handles/0xHarry.json
  _data/handles/avatars/0xHarry.jpeg
Labels: app-warden

#2603 Register warden JosepBove
  _data/handles/JosepBove.json
Labels: app-warden

#2617 Register warden HomoCryptoErectus
  _data/handles/HomoCryptoErectus.json
  _data/handles/avatars/HomoCryptoErectus.png
Labels: app-warden

#2608 Register warden Turalaliv
  _data/handles/Turalaliv.json
  _data/handles/avatars/Turalaliv.jpeg
Labels: app-warden

#2613 Register warden i0001
  _data/handles/i0001.json
Labels: app-warden

#2624 Register warden jaxcoder
  _data/handles/avatars/jaxcoder.png
  _data/handles/jaxcoder.json
Labels: app-warden

#2628 Register warden Keen_Sheen
  _data/handles/Keen_Sheen.json
Labels: app-warden

#2630 Update warden grGred
  _data/handles/grGred.json
Labels: re-registration

#2256 Add warden Raw_Natural
  _data/handles/Raw_Natural.json
  _data/handles/avatars/Raw_Natural.jpeg
Labels: app-warden

#2632 Update warden 0xkatana
  _data/handles/0xkatana.json
Labels: re-registration

#2634 Register warden mancingcrypto
  _data/handles/avatars/mancingcrypto.png
  _data/handles/mancingcrypto.json
Labels: app-warden

#2635 Update warden reassor
  _data/handles/reassor.json
Labels: re-registration

#2636 Update warden Tadashi
  _data/handles/Tadashi.json
Labels: re-registration

#2640 Update warden Kun
  _data/handles/Kun.json
Labels: re-registration

#2644 Update warden apostle0x01
  _data/handles/apostle0x01.json
Labels: re-registration

#2645 Update warden robee
  _data/handles/robee.json
Labels: re-registration

#2638 Register warden onion
  _data/handles/onion.json
Labels: app-warden

#2646 Register warden lukaprini
  _data/handles/lukaprini.json
Labels: app-warden

#2647 Register warden shog00n
  _data/handles/shog00n.json
Labels: app-warden

#2649 Update warden antonttc
  _data/handles/antonttc.json
Labels: re-registration

#2652 Update warden Noah3o6
  _data/handles/Noah3o6.json
Labels: re-registration

#2654 Update warden RedOneN
  _data/handles/RedOneN.json
Labels: re-registration

#2656 Update warden Fitraldys
  _data/handles/Fitraldys.json
Labels: re-registration

#2657 Update warden masterchief
  _data/handles/masterchief.json
Labels: re-registration

#2658 Update warden mauricio1802
  _data/handles/mauricio1802.json
Labels: re-registration

#2660 Update warden tintin
  _data/handles/tintin.json
Labels: re-registration

#2661 Register warden y1cunhui
  _data/handles/avatars/y1cunhui.jpeg
  _data/handles/y1cunhui.json
Labels: app-warden

#2648 Register warden timur_guvenkaya
  _data/handles/timur_guvenkaya.json
Labels: app-warden

#2662 Update warden cloudjunky
  _data/handles/cloudjunky.json
Labels: re-registration

#2335 Add warden Green
  _data/handles/dannyg.json
Labels: app-warden

#2651 Register warden 0xpranav
  _data/handles/0xpranav.json
Labels: app-warden

#2596 Register warden ZaharinaBF
  _data/handles/ZaharinaBF.json
Labels: app-warden

#2643 Register warden vyecanfly
  _data/handles/vyecanfly.json
Labels: app-warden

#2663 Update warden PPrieditis
  _data/handles/PPrieditis.json
Labels: re-registration

#2665 Update warden joestakey
  _data/handles/joestakey.json
Labels: re-registration

#2666 Register warden svskaushik
  _data/handles/svskaushik.json
Labels: app-warden

#2668 Register warden DMoore
  _data/handles/DMoore.json
Labels: app-warden

#2669 Register warden ylv
  _data/handles/ylv.json
Labels: app-warden

#2670 Register warden doddle0x
  _data/handles/avatars/doddle0x.png
  _data/handles/doddle0x.json
Labels: app-warden

#2671 Register warden jtseng
  _data/handles/jtseng.json
Labels: app-warden

#2673 Update warden horsefacts
  _data/handles/horsefacts.json
Labels: re-registration

#2674 Register warden nonsense_eth
  _data/handles/avatars/nonsense_eth.jpeg
  _data/handles/nonsense_eth.json
Labels: app-warden

#2676 Register warden kidwenggx
  _data/handles/avatars/kidwenggx.png
  _data/handles/kidwenggx.json
Labels: app-warden

#2677 Register warden Sneakyninja0129
  _data/handles/Sneakyninja0129.json
Labels: app-warden

#2678 Register warden fuloXX
  _data/handles/fuloXX.json
Labels: app-warden

#2679 Register warden infosec_us_team
  _data/handles/avatars/infosec_us_team.jpeg
  _data/handles/infosec_us_team.json
Labels: app-warden

#2682 Update warden 0xkowloon
  _data/handles/0xkowloon.json
Labels: re-registration

#2687 Register warden bitorhugo
  _data/handles/bitorhugo.json
Labels: app-warden

#2685 Register warden grumpytTofu
  _data/handles/grumpyTofu.json
Labels: app-warden

#2684 Register warden paulbraganza
  _data/handles/paulbraganza.json
Labels: app-warden

#2683 Register warden Morkle
  _data/handles/Morkle.json
  _data/handles/avatars/Morkle.jpeg
Labels: app-warden

#2680 Update warden grrwahrr
  _data/handles/grrwahrr.json
Labels: re-registration

#2689 Update warden _Adam
  _data/handles/_Adam.json
Labels: re-registration

#2690 Update warden async
  _data/handles/async.json
Labels: re-registration

#2695 Register warden Cheeezzyyyy
  _data/handles/Cheeezzyyyy.json
  _data/handles/avatars/Cheeezzyyyy.jpeg
Labels: app-warden

#2681 Register warden 0xHinthunter
  _data/handles/0xHinthunter.json
Labels: app-warden

#2697 Register warden muhammadhassan
  _data/handles/muhammadhassan.json
Labels: app-warden

#2699 Register warden CRYP70
  _data/handles/CRYP70.json
  _data/handles/avatars/CRYP70.jpeg
Labels: app-warden

#2698 Register warden kotsmile
  _data/handles/avatars/kotsmile.jpeg
  _data/handles/kotsmile.json
Labels: app-warden

#2693 Update warden pedroais
  _data/handles/pedroais.json
Labels: re-registration

#2701 Update warden Kenshin
  _data/handles/Kenshin.json
Labels: re-registration

#2700 Update warden kenta
  _data/handles/kenta.json
Labels: re-registration

#2704 Register warden albincsergo
  _data/handles/albincsergo.json
Labels: app-warden

#2705 Update warden chatch
  _data/handles/chatch.json
Labels: re-registration

#2709 Update warden xiaoming90
  _data/handles/xiaoming90.json
Labels: re-registration

#2711 Update warden sashik_eth
  _data/handles/sashik_eth.json
Labels: re-registration

#2714 Update warden philogy
  _data/handles/philogy.json
Labels: re-registration

#2716 Update warden saian
  _data/handles/saian.json
Labels: re-registration

#2717 Register warden Doba
  _data/handles/Doba.json
Labels: app-warden

#2719 Update warden ak1
  _data/handles/ak1.json
Labels: re-registration

#2720 Update warden LordHeb
  _data/handles/LordHeb.json
Labels: re-registration

#2723 Update warden Ch_301
  _data/handles/Ch_301.json
Labels: re-registration

#2721 Register warden seblw
  _data/handles/seblw.json
Labels: app-warden

#2724 Update warden UnusualTurtle
  _data/handles/UnusualTurtle.json
Labels: re-registration

#2725 Update warden datapunk
  _data/handles/datapunk.json
Labels: re-registration

#2727 Update warden gzeon
  _data/handles/gzeon.json
Labels: re-registration

#2729 Update warden saneryee
  _data/handles/saneryee.json
Labels: re-registration

#2738 Update warden DecorativePineapple
  _data/handles/DecorativePineapple.json
Labels: re-registration

#2735 Register warden rbserver
  _data/handles/rbserver.json
Labels: app-warden

#2742 Register warden tofunmi
  _data/handles/avatars/tofunmi.jpeg
  _data/handles/tofunmi.json
Labels: app-warden

#2741 Register warden DimitarDimitrov
  _data/handles/DimitarDimitrov.json
Labels: app-warden

#2710 Register warden 0x09GTO
  _data/handles/0x09GTO.json
Labels: app-warden

#2745 Update warden 0xriver
  _data/handles/0xriver.json
Labels: re-registration

#2748 Register warden Vexjon
  _data/handles/Vexjon.json
Labels: app-warden

#2740 Register warden Franfran
  _data/handles/Franfran.json
  _data/handles/avatars/Franfran.png
Labels: app-warden

#2756 Register warden brgltd
  _data/handles/brgltd.json
Labels: app-warden

#2750 Register warden CHAOZ
  _data/handles/CHAOZ.json
  _data/handles/avatars/CHAOZ.jpeg
Labels: app-warden

#2760 Register warden caventa
  _data/handles/caventa.json
Labels: app-warden

#2768 Import fetch
  functions/apply-for-judge.js
Labels: ready for review, quick fix

#2772 Update warden n0tspam
  _data/handles/n0tspam.json
Labels: re-registration

#2773 Update warden shw
  _data/handles/shw.json
Labels: re-registration

#2755 Register warden danykillyou
  _data/handles/dannyphantom.json
Labels: app-warden

#2780 Register warden calebbweaver
  _data/handles/calebbweaver.json
Labels: app-warden

#2782 Update warden shri4net
  _data/handles/shri4net.json
Labels: re-registration

#2783 Register warden Dustz
  _data/handles/Dustz.json
Labels: app-warden

#2784 Register warden mattarad
  _data/handles/avatars/mattarad.png
  _data/handles/mattarad.json
Labels: app-warden

#2787 Register warden M001
  _data/handles/M001.json
Labels: app-warden

#2789 Register warden MEP
  _data/handles/MEP.json
  _data/handles/avatars/MEP.jpeg
Labels: app-warden

#2792 Update warden Bruhhh
  _data/handles/Bruhhh.json
Labels: re-registration

#2769 Register warden kyteg
  _data/handles/kyteg.json
Labels: app-warden

#2794 Update warden cogitoergosumsw
  _data/handles/cogitoergosumsw.json
Labels: re-registration

#2797 Update warden sahar
  _data/handles/sahar.json
Labels: re-registration

#2798 Update warden Kong
  _data/handles/Kong.json
Labels: re-registration

#2799 Update warden Saw-mon_and_Natalie
  _data/handles/Saw-mon_and_Natalie.json
Labels: re-registration

#2802 Register warden 0xdanial
  _data/handles/0xdanial.json
  _data/handles/avatars/0xdanial.jpeg
Labels: app-warden

#2804 Register warden DoryZaih
  _data/handles/DoryZaih.json
Labels: app-warden

#2803 Register warden benbaessler
  _data/handles/benbaessler.json
Labels: app-warden

#2806 Register warden 0x040
  _data/handles/0x040.json
Labels: app-warden

#2811 Register warden august
  _data/handles/august.json
Labels: app-warden

#2812 Update warden bbrho
  _data/handles/bbrho.json
Labels: re-registration

#2767 Register warden dreth
  _data/handles/avatars/dreth.png
  _data/handles/dreth.json
Labels: app-warden

#2823 Register warden Critias
  _data/handles/Critias.json
  _data/handles/avatars/Critias.jpeg
Labels: app-warden

#2821 Register warden Viksaa39
  _data/handles/Viksaa39.json
  _data/handles/avatars/Viksaa39.png
Labels: app-warden

#2819 Register warden wilytama
  _data/handles/wilytama.json
Labels: app-warden

#2817 Register warden quinnmanning4
  _data/handles/avatars/quinnmanning4.png
  _data/handles/quinnmanning4.json
Labels: app-warden

#2801 Register warden donosonaumczuk
  _data/handles/donosonaumczuk.json
Labels: app-warden

#2754 Register warden BIDONGLING
  _data/handles/BIDONGLING.json
  _data/handles/avatars/BIDONGLING.jpeg
Labels: app-warden

#2733 Register warden chris19061976
  _data/handles/chris19061976.json
Labels: app-warden

#2828 Register warden Loggy
  _data/handles/Loggy.json
Labels: app-warden

#2829 Register warden panprog
  _data/handles/panprog.json
Labels: app-warden
