Repository code-423n4/code423n4.com, pull requests merged in 2022-06, with the labels that each got.

#2047 Update messaging for protected pages
  src/components/Dropdown.module.scss
  src/components/Login/Login.module.scss
  src/components/Login/Login.tsx
  src/components/Modal.js
  src/components/reporter/SubmitFindings.js
  src/pages/register-team.tsx
  src/styles/modal.css
  static/images/meta-mask-logo.svg
  static/images/sign-out.svg
  static/images/wallet-connect-logo.svg
Labels: enhancement, ready for review

#1755 Add warden peanut2019
  _data/handles/avatars/peanut2019.jpeg
  _data/handles/peanut2019.json
Labels: app-warden

#1802 Add warden Soosh
  _data/handles/Soosh.json
Labels: app-warden

#2077 Add warden SSDD
  _data/handles/SSDD.json
Labels: app-warden

#1953 Add warden Knight
  _data/handles/Knight.json
  _data/handles/avatars/Knight.jpeg
Labels: app-warden

#2080 Add warden engn33r
  _data/handles/avatars/engn33r.jpeg
  _data/handles/engn33r.json
Labels: app-warden

#2069 Fetch associated team to a given user
  functions/get-team.ts
  src/hooks/UserContext.tsx
Labels: enhancement, ready for review

#2059 Add warden durainSausage
  _data/handles/durainSausage.json
Labels: app-warden

#2113 Add warden chatch
  _data/handles/chatch.json
Labels: app-warden

#2111 Add warden yoni10marco
  _data/handles/yoni10marco.json
Labels: app-warden

#2095 Add warden lfzkoala
  _data/handles/avatars/lfzkoala.jpeg
  _data/handles/lfzkoala.json
Labels: app-warden

#2122 Add warden charlesjhongc
  _data/handles/avatars/charlesjhongc.jpeg
  _data/handles/charlesjhongc.json
Labels: app-warden

#2094 Add warden wuestholz
  _data/handles/wuestholz.json
Labels: app-warden

#2117 Add warden grGred
  _data/handles/grGred.json
Labels: app-warden

#2118 Fix markdown syntax
  _data/reports/2022-04-backd.md
  _data/reports/2022-04-dualityfocus.md
  gatsby-config.js
Labels: ready for review, quick fix

#2129 Add warden natzuu
  _data/handles/avatars/natzuu.jpeg
  _data/handles/natzuu.json
Labels: app-warden

#2128 Add warden 0xriver
  _data/handles/0xriver.json
Labels: app-warden

#2124 Add warden IM4G11R3
  _data/handles/IM4G11R3.json
Labels: app-warden

#2099 Re-work reset registration form
  src/components/Modal.tsx
  src/components/RegistrationForm.tsx
  src/components/reporter/SubmitFindings.js
  src/hooks/ModalContext.tsx
  src/pages/register.tsx
Labels: enhancement, ready for review

#2132 Add warden ZOUVIER
  _data/handles/ZOUVIER.json
  _data/handles/avatars/ZOUVIER.png
Labels: app-warden

#2131 Add warden auditor0517
  _data/handles/auditor0517.json
Labels: app-warden

#2093 Add toaster on login promises
  functions/get-team.ts
  src/components/Login/Login.tsx
  src/hooks/UserContext.tsx
Labels: enhancement, ready for review, UX/UI

#2140 Add warden izhuer
  _data/handles/izhuer.json
Labels: app-warden

#2081 Text area limit
  .gitignore
  src/components/reporter/SubmitFindings.js
  src/components/reporter/widgets/TextArea.js
  src/components/reporter/widgets/Widget.js
  src/components/reporter/widgets/Widgets.module.scss
  src/pages/help.js
Labels: enhancement, ready for review

#2143 Add warden jumbo
  _data/handles/avatars/jumbo.jpeg
  _data/handles/jumbo.json
Labels: app-warden

#2144 Add warden Bnke0x0
  _data/handles/Bnke0x0.json
Labels: app-warden

#2141 Add warden Trumpero
  _data/handles/Trumpero.json
Labels: app-warden

#2114 Add warden 8olidity
  _data/handles/8olidity.json
Labels: app-warden

#2151 Add warden VenC
  _data/handles/VenC.json
Labels: app-warden

#2158 Add warden pavankv
  _data/handles/avatars/pavankv.jpeg
  _data/handles/pavankv.json
Labels: app-warden

#2156 Add warden 0xSolus
  _data/handles/0xSolus.json
Labels: app-warden

#2164 Add warden FudgyDRS
  _data/handles/FudgyDRS.json
  _data/handles/avatars/FudgyDRS.jpeg
Labels: app-warden

#2165 Add warden ta_da_
  _data/handles/ta_da_.json
Labels: app-warden

#2166 Add warden Lambda
  _data/handles/Lambda.json
Labels: app-warden

#2155 Add warden ItsNio
  _data/handles/ItsNio.json
Labels: app-warden

#2145 Add warden h4t4way
  _data/handles/h4t4way.json
Labels: app-warden

#2167 Add warden ladboy233
  _data/handles/ladboy233.json
Labels: app-warden

#2172 Add warden exd0tpy
  _data/handles/avatars/exd0tpy.png
  _data/handles/exd0tpy.json
Labels: app-warden

#2169 Add warden qiaoqiao
  _data/handles/qiaoqiao.json
Labels: app-warden

#2176 Add warden georgeroman
  _data/handles/georgeroman.json
Labels: app-warden

#2185 Add warden 0xYarOS1aV
  _data/handles/0xYarOS1aV.json
Labels: app-warden

#2168 Add warden brainfuzz
  _data/handles/brainfuzz.json
Labels: app-warden

#2191 Add warden apostle0x01
  _data/handles/apostle0x01.json
  _data/handles/avatars/apostle0x01.jpeg
Labels: app-warden

#2180 Fix avatar size
  src/components/LeaderboardHandle.js
Labels: ready for review, UX/UI

#2216 Add warden SamEd
  _data/handles/SamEd.json
  _data/handles/avatars/SamEd.png
Labels: app-warden

#2213 Add warden obtarian
  _data/handles/obtarian.json
Labels: app-warden

#2229 Add warden papr1ka2
  _data/handles/papr1ka2.json
Labels: app-warden

#2231 Add warden MouseLess
  _data/handles/MouseLess.json
  _data/handles/avatars/MouseLess.png
Labels: app-warden

#2235 Add warden jayfromthe13th
  _data/handles/avatars/jayfromthe13th.png
  _data/handles/jayfromthe13th.json
Labels: app-warden

#2210 Add warden 0xbpf
  _data/handles/0xbpf.json
Labels: app-warden

#2217 Add warden Destroyersrt
  _data/handles/Destroyersrt.json
  _data/handles/avatars/Destroyersrt.png
Labels: app-warden

#2233 Add warden wagmi
  _data/handles/wagmi.json
Labels: app-warden

#2237 Add warden Noah3o6
  _data/handles/Noah3o6.json
  _data/handles/avatars/Noah3o6.jpeg
Labels: app-warden

#2232 2197 better sign message on login
  src/components/Login/Login.tsx
  src/components/RegistrationForm.tsx
Labels: ready for review

#2220 2204 not enough contrast on connect links
  src/components/Dropdown.module.scss
Labels: ready for review

#2219 Mark current users "confirmed"
  documentation/MoralisInstructions.md
  moralis/cloud.js
  src/pages/confirm-account.tsx
Labels: ready for review

#2260 Add warden Haruxe
  _data/handles/Haruxe.json
  _data/handles/avatars/Haruxe.png
Labels: app-warden

#2254 Add warden AtomicAzzaz
  _data/handles/AtomicAzzaz.json
  _data/handles/avatars/AtomicAzzaz.jpeg
Labels: app-warden

#2264 Add warden JuicyNuts
  _data/handles/JuicyNuts.json
  _data/handles/avatars/JuicyNuts.jpeg
Labels: app-warden

#2265 Add warden ak1
  _data/handles/ak1.json
Labels: app-warden

#2244 Add warden grrwahrr
  _data/handles/grrwahrr.json
Labels: app-warden

#2262 Add warden datapunk
  _data/handles/datapunk.json
Labels: app-warden

#2215 Add warden Touta
  _data/handles/Touta8989.json
Labels: app-warden

#2247 Add warden EthLedger
  _data/handles/EthLedger.json
Labels: app-warden

#2259 Add warden Limbooo
  _data/handles/Limbooo.json
  _data/handles/avatars/Limbooo.png
Labels: app-warden

#2270 Rename warden to tomtsaoao
  _data/handles/JuicyNuts.json
  _data/handles/avatars/tomtsaoao.jpeg
  _data/handles/tomtsaoao.json
Labels: app-warden

#2271 Add warden hrishibhat
  _data/handles/avatars/hrishibhat.jpeg
  _data/handles/hrishibhat.json
Labels: app-warden

#2277 Add warden vyorkin
  _data/handles/avatars/vyorkin.jpeg
  _data/handles/vyorkin.json
Labels: app-warden

#2266 Add warden Vicky13
  _data/handles/Vicky13.json
Labels: app-warden

#2278 Add warden Tutturu
  _data/handles/Tutturu.json
  _data/handles/avatars/Tutturu.jpeg
Labels: app-warden

#2280 Add warden qwen
  _data/handles/qwen.json
Labels: app-warden

#2284 Add warden azanux
  _data/handles/azanux.json
Labels: app-warden

#2279 Add warden neumo
  _data/handles/avatars/neumo.png
  _data/handles/neumo.json
Labels: app-warden

#2275 Add warden m_Rassska
  _data/handles/avatars/m_Rassska.png
  _data/handles/m_Rassska.json
Labels: app-warden

#2282 Add warden xoxoverflow
  _data/handles/avatars/xoxoverflow.png
  _data/handles/xoxoverflow.json
Labels: app-warden

#2234 Reset logic for team registration + validation
  functions/register-team.ts
  src/components/RegistrationForm.tsx
  src/components/TeamRegistrationForm.tsx
  src/pages/register-team.tsx
Labels: ready for review

#2292 Add warden 0xdeadf4ce
  _data/handles/0xdeadf4ce.json
  _data/handles/avatars/0xdeadf4ce.jpeg
Labels: app-warden

#2276 Add warden sorawit
  _data/handles/sorawit.json
Labels: app-warden

#2283 Add warden 0xzuhaibmohd
  _data/handles/0xzuhaibmohd.json
  _data/handles/avatars/0xzuhaibmohd.jpeg
Labels: app-warden

#2300 Add warden DavideSilva
  _data/handles/DavideSilva.json
  _data/handles/avatars/DavideSilva.jpeg
Labels: app-warden

#2273 Add warden Naxxar
  _data/handles/Naxxar.json
Labels: app-warden

#2296 Add warden resende
  _data/handles/resende.json
Labels: app-warden

#2297 Add warden skoorch
  _data/handles/avatars/skoorch.png
  _data/handles/skoorch.json
Labels: app-warden

#2309 Add warden Ephraim
  _data/handles/Ephraim.json
  _data/handles/avatars/Ephraim.png
Labels: app-warden

#2303 Add warden littlefrankie
  _data/handles/littlefrankie.json
Labels: app-warden

#2181 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/ux-ui.md
Labels: enhancement, ready for review

#2310 Add warden rayedsikder
  _data/handles/rayedsikder.json
Labels: app-warden

#2313 Add warden LeoGold
  _data/handles/LeoGold.json
  _data/handles/avatars/LeoGold.png
Labels: app-warden

#2314 Add warden tank
  _data/handles/tank.json
Labels: app-warden

#2312 Add warden topsniper496
  _data/handles/topsniper496.json
Labels: app-warden

#2322 Add warden Peep
  _data/handles/Peep.json
  _data/handles/avatars/Peep.jpeg
Labels: app-warden

#2302 Add warden cRat1st0s
  _data/handles/cRat1st0s.json
Labels: app-warden

#2327 Add warden ajtra
  _data/handles/ajtra.json
Labels: app-warden

#2316 Add warden JeremiahNoah
  _data/handles/JeremiahNoah.json
Labels: app-warden

#2328 Add warden Chandr
  _data/handles/Chandr.json
Labels: app-warden

#2223 2201 warden can steal identity of another user
  functions/apply-for-certified-contributor.ts
  functions/apply-for-judge.js
  src/components/ProtectedPage.tsx
  src/components/RegistrationForm.tsx
  src/components/form/Form.module.scss
  src/components/reporter/SubmitFindings.js
  src/components/reporter/widgets/Widgets.module.scss
  src/pages/certified-contributor-application.tsx
  src/pages/judge-application.js
  src/pages/register-team.tsx
  src/templates/ReportForm.js
Labels: ready for review

#2315 Add warden punchi
  _data/handles/punchi.json
Labels: app-warden

#2318 Add warden SaharAP
  _data/handles/SaharAP.json
  _data/handles/avatars/SaharAP.png
Labels: app-warden

#2325 Add warden Ch_301
  _data/handles/Ch_301.json
  _data/handles/avatars/Ch_301.png
Labels: app-warden

#2224 2200 dos code4rena website
  functions/register-team.ts
  functions/register-warden.js
  functions/submit-finding.js
  src/components/Login/UserDropdown.tsx
  src/components/RegistrationForm.tsx
  src/components/TeamRegistrationForm.tsx
  src/components/reporter/widgets/WardenField.js
  src/components/reporter/widgets/WardenField.module.scss
  src/pages/register-team.tsx
Labels: ready for review

#2330 Check if user Handle is malicious
  functions/get-team.ts
  functions/get-user.ts
Labels: ready for review

#2332 Add warden 0xlowki
  _data/handles/0xlowki.json
Labels: app-warden

#2336 Add warden 0xArshia
  _data/handles/0xArshia.json
  _data/handles/avatars/0xArshia.jpeg
Labels: app-warden

#2252 Add warden Haidder
  _data/handles/Haidder.json
Labels: app-warden

#2341 Add warden PhilippeG
  _data/handles/PhilippeG.json
  _data/handles/avatars/PhilippeG.png
Labels: app-warden

#2344 Add warden Kun
  _data/handles/Kun.json
  _data/handles/avatars/Kun.jpeg
Labels: app-warden

#2295 Add warden veldt
  _data/handles/avatars/veldt.jpeg
  _data/handles/veldt.json
Labels: app-warden

#2342 Add warden 0xA5DF
  _data/handles/0xA5DF.json
  _data/handles/avatars/0xA5DF.jpeg
Labels: app-warden

#2347 Add warden 0xdonva
  _data/handles/0xdonva.json
  _data/handles/avatars/0xdonva.png
Labels: app-warden

#2350 Fix validation on registration form
  src/components/RegistrationForm.tsx
Labels: ready for review

#2351 Add warden 0xSky
  _data/handles/0xSky.json
  _data/handles/avatars/0xSky.jpeg
Labels: app-warden

#2352 Add warden Koen
  _data/handles/Koen.json
Labels: app-warden

#2356 Add warden bitnulleins
  _data/handles/bitnulleins.json
Labels: app-warden

#2359 Add warden Grimreap3r
  _data/handles/Grimreap3r.json
Labels: app-warden

#2360 Add warden Aymen0909
  _data/handles/Aymen0909.json
  _data/handles/avatars/Aymen0909.jpeg
Labels: app-warden

#2372 Update warden StyxRave
  _data/handles/StyxRave.json
Labels: re-registration

#2399 Update warden ellahi
  _data/handles/ellahi.json
Labels: re-registration

#2374 Update warden ilan
  _data/handles/ilan.json
Labels: re-registration

#2375 Update warden Koen
  _data/handles/Koen.json
Labels: re-registration

#2376 Update warden Kaiziron
  _data/handles/Kaiziron.json
Labels: re-registration

#2377 Update warden simon135
  _data/handles/simon135.json
Labels: re-registration

#2378 Update warden hansfriese
  _data/handles/hansfriese.json
Labels: re-registration

#2379 Update warden natzuu
  _data/handles/natzuu.json
Labels: re-registration

#2380 Update warden berndartmueller
  _data/handles/berndartmueller.json
Labels: re-registration

#2382 Update warden ajtra
  _data/handles/ajtra.json
Labels: re-registration

#2383 Update warden JustaTree
  _data/handles/JustaTree.json
Labels: re-registration

#2384 Update warden smiling_heretic
  _data/handles/smiling_heretic.json
Labels: re-registration

#2385 Update warden alan724
  _data/handles/alan724.json
Labels: re-registration

#2387 Update warden SecureZeroX
  _data/handles/SecureZeroX.json
Labels: re-registration

#2388 Update warden Chom
  _data/handles/Chom.json
Labels: re-registration

#2389 Update warden mrpathfindr
  _data/handles/mrpathfindr.json
Labels: re-registration

#2390 Update warden auditor0517
  _data/handles/auditor0517.json
Labels: re-registration

#2391 Update warden 0v3rf10w
  _data/handles/0v3rf10w.json
Labels: re-registration

#2392 Update warden defsec
  _data/handles/defsec.json
Labels: re-registration

#2393 Update warden savi0ur
  _data/handles/savi0ur.json
Labels: re-registration

#2413 Update warden 0xdonva
  _data/handles/0xdonva.json
Labels: re-registration

#2395 Update warden pashov
  _data/handles/pashov.json
Labels: re-registration

#2397 Update warden unforgiven
  _data/handles/unforgiven.json
Labels: re-registration

#2400 Update warden OriDabush
  _data/handles/OriDabush.json
Labels: re-registration

#2401 Update warden Lambda
  _data/handles/Lambda.json
Labels: re-registration

#2408 Update warden HardlyDifficult
  _data/handles/HardlyDifficult.json
Labels: re-registration

#2406 Update warden samruna
  _data/handles/samruna.json
Labels: re-registration

#2411 Update warden Yiko
  _data/handles/Yiko.json
Labels: re-registration

#2402 Update warden shakedwinder
  _data/handles/shakedwinder.json
Labels: re-registration

#2415 Update warden cryptphi
  _data/handles/cryptphi.json
Labels: re-registration

#2412 Update warden ignacio
  _data/handles/ignacio.json
Labels: re-registration

#2416 Update warden ItsNio
  _data/handles/ItsNio.json
Labels: re-registration

#2418 Update warden 0xNineDec
  _data/handles/0xNineDec.json
Labels: re-registration

#2417 Update warden izhuer
  _data/handles/izhuer.json
Labels: re-registration

#2373 Update warden CaptainMango
  _data/handles/CaptainMango.json
Labels: re-registration
