Repository code-423n4/code423n4.com, pull requests merged in 2022-12, with the labels that each got.

#5757 Register warden sonicskye
  _data/handles/sonicskye.json
Labels: app-warden

#5751 Register warden NooNoo
  _data/handles/NooNoo.json
Labels: app-warden

#5750 Register warden bharat_nakwalm
  _data/handles/bharat_nakwalm.json
Labels: app-warden

#5749 Register warden cyberinn
  _data/handles/cyberinn.json
Labels: app-warden

#5725 Register warden greenbergz
  _data/handles/greenbergz.json
Labels: app-warden

#5760 Register warden akshaan
  _data/handles/akshaan.json
Labels: app-warden

#5764 Register warden mihaic195
  _data/handles/mihaic195.json
Labels: app-warden

#5775 Register warden bullseye
  _data/handles/avatars/bullseye.png
  _data/handles/bullseye.json
Labels: app-warden

#5772 Register warden Sileo
  _data/handles/Sileo.json
  _data/handles/avatars/Sileo.png
Labels: app-warden

#5778 Register warden yjrwkk
  _data/handles/yjrwkk.json
Labels: app-warden

#5762 Register warden chluff
  _data/handles/avatars/chluff.png
  _data/handles/chluff.json
Labels: app-warden

#5773 Register warden jacopod
  _data/handles/jacopod.json
Labels: app-warden

#5774 Register warden frizzlefrupple
  _data/handles/frizzlefrupple.json
Labels: app-warden

#5767 Register warden mahdirostami
  _data/handles/avatars/mahdirostami.jpeg
  _data/handles/mahdirostami.json
Labels: app-warden

#5765 Register warden dragoonzx
  _data/handles/dragoonzx.json
Labels: app-warden

#5777 Register warden yjrwk
  _data/handles/yjrwk.json
Labels: app-warden

#5781 Register warden matrix_0wl
  _data/handles/avatars/matrix_0wl.png
  _data/handles/matrix_0wl.json
Labels: app-warden

#5776 Register warden Arefin
  _data/handles/Arefin.json
  _data/handles/avatars/Arefin.png
Labels: app-warden

#5787 Register warden N16H7M4R3
  _data/handles/N16H7M4R3.json
Labels: app-warden

#5788 Register warden barden
  _data/handles/avatars/barden.png
  _data/handles/barden.json
Labels: app-warden

#5790 Register warden Shadowave213
  _data/handles/Shadowave213.json
  _data/handles/avatars/Shadowave213.jpeg
Labels: app-warden

#5791 Register warden alyosha
  _data/handles/alyosha.json
Labels: app-warden

#5794 Register warden 0x73696d616f
  _data/handles/0x73696d616f.json
  _data/handles/avatars/0x73696d616f.jpeg
Labels: app-warden

#5793 Register warden kuldeep
  _data/handles/kuldeep.json
Labels: app-warden

#5798 Register warden 0xIchigo
  _data/handles/0xIchigo.json
Labels: app-warden

#5797 Register warden AkashHamal0x01
  _data/handles/AkashHamal0x01.json
  _data/handles/avatars/AkashHamal0x01.jpeg
Labels: app-warden

#5795 Register warden beskay
  _data/handles/avatars/beskay.jpeg
  _data/handles/beskay.json
Labels: app-warden

#5800 Register warden Big0XDev
  _data/handles/Big0XDev.json
Labels: app-warden

#5803 Register warden stealthyz
  _data/handles/stealthyz.json
Labels: app-warden

#5796 Register warden RealIanX
  _data/handles/RealIanX.json
  _data/handles/avatars/RealIanX.jpeg
Labels: app-warden

#5734 Register warden karappolice
  _data/handles/karappolice.json
Labels: app-warden

#5806 Register warden Alla29
  _data/handles/Alla29.json
  _data/handles/avatars/Alla29.jpeg
Labels: app-warden

#5805 Register warden helios
  _data/handles/helios.json
Labels: app-warden

#5804 Register warden puffy
  _data/handles/puffy.json
Labels: app-warden

#5815 Register warden evan
  _data/handles/evan.json
Labels: app-warden

#5814 Register warden yellowBirdy
  _data/handles/avatars/yellowBirdy.jpeg
  _data/handles/yellowBirdy.json
Labels: app-warden

#5811 Register warden slvDev
  _data/handles/slvDev.json
Labels: app-warden

#5823 Register warden KrisApostolov
  _data/handles/KrisApostolov.json
Labels: app-warden

#5824 Register warden DeGatchi
  _data/handles/DeGatchi.json
  _data/handles/avatars/DeGatchi.png
Labels: app-warden

#5829 Register warden einik
  _data/handles/einik.json
Labels: app-warden

#5753 Register warden georgits
  _data/handles/georgits.json
Labels: app-warden

#5830 Register warden cucbku
  _data/handles/cucbku.json
Labels: app-warden

#5799 Register warden americosmjr
  _data/handles/americosmjr.json
  _data/handles/avatars/americosmjr.jpeg
Labels: app-warden

#5818 Register warden alymurtazamemon
  _data/handles/alymurtazamemon.json
  _data/handles/avatars/alymurtazamemon.png
Labels: app-warden

#5801 Register warden skepticalsec
  _data/handles/skepticalsec.json
Labels: app-warden

#5837 Register warden yellowcurtain
  _data/handles/yellowcurtain.json
Labels: app-warden

#5620 Register warden bluejacket
  _data/handles/bluejacket.json
Labels: app-warden

#5802 Register warden saint-rat
  _data/handles/avatars/saint-rat.png
  _data/handles/saint-rat.json
Labels: app-warden

#5838 Register warden gasperpre
  _data/handles/gasperpre.json
Labels: app-warden

#5849 Register warden serinuntius
  _data/handles/avatars/serinuntius.jpeg
  _data/handles/serinuntius.json
Labels: app-warden

#5850 Register warden mrvincere
  _data/handles/mrvincere.json
Labels: app-warden

#5784 Register warden lordagnew
  _data/handles/lordagnew.json
Labels: app-warden

#5783 Register warden dylandesrosier
  _data/handles/avatars/dylandesrosier.png
  _data/handles/dylandesrosier.json
Labels: app-warden

#5831 Register warden t-pwn
  _data/handles/t-pwn.json
Labels: app-warden

#5853 Register warden therahulpujari
  _data/handles/avatars/therahulpujari.jpeg
  _data/handles/therahulpujari.json
Labels: app-warden

#5855 Register warden Delvir0
  _data/handles/Delvir0.json
Labels: app-warden

#5871 Register warden 0x446576
  _data/handles/0x446576.json
  _data/handles/avatars/0x446576.png
Labels: app-warden

#5872 Register warden noot
  _data/handles/avatars/noot.jpeg
  _data/handles/noot.json
Labels: app-warden

#5852 Register warden KazumaHamamoto
  _data/handles/KazumaHamamoto.json
Labels: app-warden

#5874 Register warden azhar
  _data/handles/avatars/azhar.jpeg
  _data/handles/azhar.json
Labels: app-warden

#5876 Register warden 0xJJ
  _data/handles/0xJJ.json
  _data/handles/avatars/0xJJ.jpeg
Labels: app-warden

#5877 Register warden hexbyte
  _data/handles/avatars/hexbyte.jpeg
  _data/handles/hexbyte.json
Labels: app-warden

#5865 Register warden Coffee_Weed
  _data/handles/Coffee_Weed.json
  _data/handles/avatars/Coffee_Weed.png
Labels: app-warden

#5862 Register warden debo
  _data/handles/debo.json
Labels: app-warden

#5885 Register warden ediv
  _data/handles/avatars/ediv.png
  _data/handles/ediv.json
Labels: app-warden

#5884 Register warden MasOnChain
  _data/handles/MasOnChain.json
  _data/handles/avatars/MasOnChain.png
Labels: app-warden

#5888 Register warden skidog
  _data/handles/skidog.json
Labels: app-warden

#5843 Ignore casing when comparing new username to existing usernames
  _data/handles/D-Squared.json
  src/components/RegistrationForm.tsx
Labels: ready for review

#5846 Register warden 0Kage
  _data/handles/0Kage.json
  _data/handles/avatars/0Kage.png
Labels: app-warden

#5896 Register warden whalegoddess
  _data/handles/whalegoddess.json
Labels: app-warden

#5895 Register warden jensen_tran
  _data/handles/jensen_tran.json
Labels: app-warden

#5898 Register warden Stengo
  _data/handles/Stengo.json
Labels: app-warden

#5900 Register warden Janio
  _data/handles/Janio.json
  _data/handles/avatars/Janio.jpeg
Labels: app-warden

#5881 Register warden sangf41999
  _data/handles/avatars/sangf41999.jpeg
  _data/handles/sangf41999.json
Labels: app-warden

#5904 Register warden Qeew
  _data/handles/Qeew.json
  _data/handles/avatars/Qeew.png
Labels: app-warden

#5905 Register warden gkrqd
  _data/handles/gkrqd.json
Labels: app-warden

#5907 Register warden Bobface
  _data/handles/Bobface.json
  _data/handles/avatars/Bobface.jpeg
Labels: app-warden

#5908 Register warden 0xTraub
  _data/handles/0xTraub.json
Labels: app-warden

#5789 Register warden luciana
  _data/handles/avatars/luciana.jpeg
  _data/handles/luciana.json
Labels: app-warden

#5909 Register warden skinheadz
  _data/handles/avatars/skinheadz.jpeg
  _data/handles/skinheadz.json
Labels: app-warden

#5893 Register warden kunala
  _data/handles/avatars/kunala.jpeg
  _data/handles/kunala.json
Labels: app-warden

#5911 Register warden K1ra
  _data/handles/K1ra.json
  _data/handles/avatars/K1ra.jpeg
Labels: app-warden

#5924 Register warden jobean89
  _data/handles/jobean89.json
Labels: app-warden

#5923 Register warden harisnabeel
  _data/handles/avatars/harisnabeel.jpeg
  _data/handles/harisnabeel.json
Labels: app-warden

#5922 Register warden adarji
  _data/handles/adarji.json
  _data/handles/avatars/adarji.png
Labels: app-warden

#5921 Register warden flamuri
  _data/handles/flamuri.json
Labels: app-warden

#5920 Register warden faizannehal
  _data/handles/faizannehal.json
Labels: app-warden

#5919 Register warden Jayus
  _data/handles/Jayus.json
Labels: app-warden

#5916 Register warden 019EC6E2
  _data/handles/019EC6E2.json
  _data/handles/avatars/019EC6E2.png
Labels: app-warden

#5934 Register warden greggy
  _data/handles/greggy.json
Labels: app-warden

#5928 Update warden haku
  _data/handles/haku.json
Labels: re-registration

#5927 Register warden BatSecurity
  _data/handles/BatSecurity.json
Labels: app-warden

#5948 Register warden daikai
  _data/handles/avatars/daikai.png
  _data/handles/daikai.json
Labels: app-warden

#5947 Register warden Michaels
  _data/handles/Michaels.json
  _data/handles/avatars/Michaels.png
Labels: app-warden

#5946 Register warden Fjorin
  _data/handles/Fjorin.json
Labels: app-warden

#5944 Register warden Tony_banks
  _data/handles/Tony_banks.json
  _data/handles/avatars/Tony_banks.jpeg
Labels: app-warden

#5940 Register warden brajon
  _data/handles/avatars/brajon.jpeg
  _data/handles/brajon.json
Labels: app-warden

#5941 Register warden tanmay35
  _data/handles/tanmay35.json
Labels: app-warden

#5949 Register warden cardene
  _data/handles/avatars/cardene.jpeg
  _data/handles/cardene.json
Labels: app-warden

#5950 Register warden meriken
  _data/handles/meriken.json
Labels: app-warden

#5951 Register warden yawn
  _data/handles/yawn.json
Labels: app-warden

#5955 Register warden yosuke
  _data/handles/avatars/yosuke.jpeg
  _data/handles/yosuke.json
Labels: app-warden

#5957 Register warden cotoneum
  _data/handles/avatars/cotoneum.jpeg
  _data/handles/cotoneum.json
Labels: app-warden

#5931 Register warden wallstreetvilkas
  _data/handles/avatars/wallstreetvilkas.jpeg
  _data/handles/wallstreetvilkas.json
Labels: app-warden

#5926 Register warden keit
  _data/handles/keit.json
Labels: app-warden

#5958 Register warden SOlgaS
  _data/handles/SOlgaS.json
  _data/handles/avatars/SOlgaS.png
Labels: app-warden

#5959 Register warden ahayashi
  _data/handles/ahayashi.json
Labels: app-warden

#5961 Register warden mookimgo
  _data/handles/mookimgo.json
Labels: app-warden

#5962 Register warden shadows
  _data/handles/shadows.json
Labels: app-warden

#5963 Register warden kevin_katsu
  _data/handles/avatars/kevin_katsu.png
  _data/handles/kevin_katsu.json
Labels: app-warden

#5965 Register warden RahulBlatz
  _data/handles/RahulBlatz.json
Labels: app-warden

#5973 Register warden izhelyazkov
  _data/handles/izhelyazkov.json
Labels: app-warden

#5972 Register warden marcelomorgado
  _data/handles/marcelomorgado.json
Labels: app-warden

#5971 Register warden Apocalyptic
  _data/handles/Apocalyptic.json
Labels: app-warden

#5969 Register warden xrY
  _data/handles/xrY.json
Labels: app-warden

#5960 Register warden QASH
  _data/handles/QASH.json
Labels: app-warden

#5975 Register warden BAHOZ
  _data/handles/BAHOZ.json
Labels: app-warden

#5844 Register warden 0xbereket
  _data/handles/0xbereket.json
Labels: app-warden

#5937 Register warden nnon
  _data/handles/avatars/nnon.jpeg
  _data/handles/nnon.json
Labels: app-warden

#5964 Register warden masaru
  _data/handles/masaru.json
Labels: app-warden

#5980 Register warden mugi
  _data/handles/avatars/mugi.png
  _data/handles/mugi.json
Labels: app-warden

#5989 Register warden magrisya
  _data/handles/magrisya.json
Labels: app-warden

#5991 Register warden G2
  _data/handles/G2.json
  _data/handles/avatars/G2.png
Labels: app-warden

#5992 Register warden 0xGusMcCrae
  _data/handles/0xGusMcCrae.json
  _data/handles/avatars/0xGusMcCrae.jpeg
Labels: app-warden

#5990 Register warden bugcontract
  _data/handles/bugcontract.json
Labels: app-warden

#5966 Register warden Shunshow
  _data/handles/Shunshow.json
  _data/handles/avatars/Shunshow.png
Labels: app-warden

#5994 Register warden gperezalba
  _data/handles/gperezalba.json
Labels: app-warden

#5999 Register warden Zarf
  _data/handles/Zarf.json
Labels: app-warden

#5997 Register warden Zac
  _data/handles/Zac.json
Labels: app-warden

#5998 Register warden bheau
  _data/handles/bheau.json
Labels: app-warden

#6001 Register warden woollie
  _data/handles/woollie.json
Labels: app-warden

#6002 Register warden sk8erboy
  _data/handles/sk8erboy.json
Labels: app-warden

#6009 Register warden Fon
  _data/handles/Fon.json
Labels: app-warden

#5809 Register warden CaptainWoof
  _data/handles/CaptainWoof.json
Labels: app-warden

#6006 Register warden junya
  _data/handles/avatars/junya.png
  _data/handles/junya.json
Labels: app-warden

#6005 Register warden lulox
  _data/handles/avatars/lulox.jpeg
  _data/handles/lulox.json
Labels: app-warden

#6024 Register warden mvsashi
  _data/handles/mvsashi.json
Labels: app-warden

#6022 Register warden d4r3d3v1l
  _data/handles/d4r3d3v1l.json
Labels: app-warden

#6021 Register warden mabuk
  _data/handles/mabuk.json
Labels: app-warden

#6017 Register warden askariabidi
  _data/handles/askariabidi.json
  _data/handles/avatars/askariabidi.png
Labels: app-warden

#6010 Register warden faiqkhan
  _data/handles/avatars/faiqkhan.jpeg
  _data/handles/faiqkhan.json
Labels: app-warden

#6026 Register warden kartkhira
  _data/handles/kartkhira.json
Labels: app-warden

#6031 Register warden maxcoto
  _data/handles/avatars/maxcoto.jpeg
  _data/handles/maxcoto.json
Labels: app-warden

#6032 Register warden GreedyGoblin
  _data/handles/greedyGoblin.json
Labels: app-warden

#6020 Register warden nstap
  _data/handles/nstap.json
Labels: app-warden

#6034 Register warden Ritzy
  _data/handles/Ritzy.json
Labels: app-warden

#6019 Register warden said
  _data/handles/said.json
Labels: app-warden

#6007 Adding hero secondary CTA
  src/components/content/HeroIndex.js
  src/styles/buttons.css
  src/styles/hero.css
  src/styles/index.css
Labels: ready for review

#5678 Register warden sath26
  _data/handles/sath26.json
Labels: app-warden

#6013 Register warden kyok1st
  _data/handles/avatars/kyok1st.png
  _data/handles/kyok1st.json
Labels: app-warden
