Repository code-423n4/code423n4.com, pull requests merged in 2023-05, with the labels that each got.

#9565 Register warden Audinarey
  _data/handles/Audinarey.json
  _data/handles/avatars/Audinarey.jpeg
Labels: app-warden

#9564 Register warden lahm00
  _data/handles/lahm00.json
Labels: app-warden

#9567 Register warden Aduttya
  _data/handles/Aduttya.json
  _data/handles/avatars/Aduttya.jpeg
Labels: app-warden

#9566 Register warden 0xb41a
  _data/handles/0xb41a.json
Labels: app-warden

#9536 Register warden 0xunlimited
  _data/handles/0xunlimited.json
Labels: app-warden

#9576 Update warden juicy
  _data/handles/juicy.json
Labels: re-registration

#9573 Register warden royalcoder
  _data/handles/royalcoder.json
Labels: app-warden

#9578 Register warden blakewh
  _data/handles/blakewh.json
Labels: app-warden

#9580 Register warden crypto586
  _data/handles/crypto586.json
Labels: app-warden

#9582 Register warden syferr
  _data/handles/avatars/syferr.png
  _data/handles/syferr.json
Labels: app-warden

#9585 Register warden dbs99
  _data/handles/dbs99.json
Labels: app-warden

#9587 Register warden AzC05
  _data/handles/AzC05.json
Labels: app-warden

#9588 Register warden shamsulhaq123
  _data/handles/shamsulhaq123.json
Labels: app-warden

#9592 Register warden sussy_hacka
  _data/handles/sussy_hacka.json
Labels: app-warden

#9510 Register warden Yeats0
  _data/handles/Yeats0.json
Labels: app-warden

#9547 Register warden brohamgoham
  _data/handles/brohamgoham.json
Labels: app-warden

#9569 Register warden NeverMind
  _data/handles/NeverMind.json
Labels: app-warden

#9589 Register warden Barrocz
  _data/handles/Barrocz.json
Labels: app-warden

#9560 Register warden borte
  _data/handles/borte.json
Labels: app-warden

#9577 Register warden burakguzel
  _data/handles/burakguzel.json
Labels: app-warden

#9597 Register warden binaryogi
  _data/handles/binaryogi.json
Labels: app-warden

#9595 Register warden TermoHash
  _data/handles/TermoHash.json
Labels: app-warden

#9599 Register warden DelerRH
  _data/handles/DelerRH.json
  _data/handles/avatars/DelerRH.jpeg
Labels: app-warden

#9598 Register warden rickyspanish
  _data/handles/rickyspanish.json
Labels: app-warden

#9570 Register warden l0j0
  _data/handles/avatars/l0j0.png
  _data/handles/l0j0.json
Labels: app-warden

#9554 Register warden rass0x4f
  _data/handles/avatars/rass0x4f.jpeg
  _data/handles/rass0x4f.json
Labels: app-warden

#9602 Register warden Shalanov
  _data/handles/Shalanov.json
Labels: app-warden

#9603 Register warden playa2
  _data/handles/avatars/Playa2.png
  _data/handles/playa2.json
Labels: app-warden

#9607 Register warden dannygfromnyc
  _data/handles/avatars/dannygfromnyc.png
  _data/handles/dannygfromnyc.json
Labels: app-warden

#9461 Add Issue type to submit form
  src/components/reporter/SubmitFindings.tsx
  src/components/reporter/findings/fields.js
  src/templates/ReportForm.tsx
  types/finding.ts
Labels: ready for review

#9606 Register warden lukenamop
  _data/handles/lukenamop.json
Labels: app-warden

#9610 Register warden xuwinnie
  _data/handles/xuwinnie.json
Labels: app-warden

#9622 Register warden 0xManishTech
  _data/handles/0xManishTech.json
  _data/handles/avatars/0xManishTech.jpeg
Labels: app-warden

#9620 Register warden Kits
  _data/handles/Kits.json
  _data/handles/avatars/Kits.png
Labels: app-warden

#9621 Register warden 0B5iDi4N
  _data/handles/0B5iDi4N.json
Labels: app-warden

#9616 Register warden LynuX
  _data/handles/LynuX.json
  _data/handles/avatars/LynuX.jpeg
Labels: app-warden

#9615 Register warden TS
  _data/handles/TS.json
Labels: app-warden

#9613 Register warden Wall-E
  _data/handles/Wall-E.json
Labels: app-warden

#9601 Register warden carlomigueldy
  _data/handles/avatars/carlomigueldy.jpeg
  _data/handles/carlomigueldy.json
Labels: app-warden

#9623 Register warden SlimyLemon
  _data/handles/SlimyLemon.json
  _data/handles/avatars/SlimyLemon.png
Labels: app-warden

#9543 Register warden mpothin
  _data/handles/mpothin.json
Labels: app-warden

#9511 Register warden hanhvn
  _data/handles/hanhvn.json
Labels: app-warden

#9642 Register warden Blockchain_Ronin
  _data/handles/Blockchain_Ronin.json
  _data/handles/avatars/Blockchain_Ronin.jpeg
Labels: app-warden

#9637 Register warden darager
  _data/handles/avatars/darager.jpeg
  _data/handles/darager.json
Labels: app-warden

#9353 Register warden leegh
  _data/handles/leegh.json
Labels: app-warden

#9618 Register warden 0xh8h
  _data/handles/0xh8h.json
Labels: app-warden

#9645 Register warden Hiflex
  _data/handles/Hiflex.json
  _data/handles/avatars/Hiflex.jpeg
Labels: app-warden

#9634 Register warden 0xHati
  _data/handles/0xHati.json
  _data/handles/avatars/0xHati.png
Labels: app-warden

#9513 Register warden glassvault
  _data/handles/glassvault.json
Labels: app-warden

#8973 Register warden Velislav4o
  _data/handles/Velislav4o.json
Labels: app-warden

#9647 Register warden CrypticShepherd
  _data/handles/CrypticShepherd.json
Labels: app-warden

#9617 Register warden tak_003
  _data/handles/tak_003.json
Labels: app-warden

#9665 Update warden patitonar
  _data/handles/patitonar.json
Labels: re-registration

#9661 Register warden Slavcheww
  _data/handles/Slavcheww.json
Labels: app-warden

#9664 Register warden dankchops
  _data/handles/dankchops.json
Labels: app-warden

#9632 Register warden DK
  _data/handles/DK.json
Labels: app-warden

#9652 Register warden 8306
  _data/handles/8306.json
Labels: app-warden

#9667 Register warden 0xlyov
  _data/handles/0xlyov.json
Labels: app-warden

#9668 Register warden pinner
  _data/handles/avatars/pinner.jpeg
  _data/handles/pinner.json
Labels: app-warden

#9648 Register warden CryptoFallen
  _data/handles/CryptoFallen.json
  _data/handles/avatars/CryptoFallen.jpeg
Labels: app-warden

#9674 Register warden eazyg
  _data/handles/eazyg.json
Labels: app-warden

#9678 Register warden TheFabled
  _data/handles/TheFabled.json
  _data/handles/avatars/TheFabled.png
Labels: app-warden

#9677 Register warden Shame
  _data/handles/Shame.json
Labels: app-warden

#9676 Register warden roflsst
  _data/handles/avatars/roflsst.png
  _data/handles/roflsst.json
Labels: app-warden

#9680 Register warden misfitD00M
  _data/handles/misfitD00M.json
Labels: app-warden

#9686 Fix label for bot races
  netlify/functions/promote-bot.ts
  netlify/functions/register-bot.ts
  netlify/functions/submit-bot-report.ts
Labels: ready for review

#9631 Register warden vipe0x
  _data/handles/vipe0x.json
Labels: app-warden

#9684 Register warden twcctop
  _data/handles/twcctop.json
Labels: app-warden

#9688 Register warden StoicTopG
  _data/handles/StoicTopG.json
  _data/handles/avatars/StoicTopG.jpeg
Labels: app-warden

#9691 Register warden user100500
  _data/handles/avatars/user100500.jpeg
  _data/handles/user100500.json
Labels: app-warden

#9692 Register warden geodude
  _data/handles/avatars/geodude.png
  _data/handles/geodude.json
Labels: app-warden

#9653 Register warden 0xMetapunk
  _data/handles/0xMetapunk.json
Labels: app-warden

#9690 Register warden Quantish
  _data/handles/Quantish.json
  _data/handles/avatars/Quantish.png
Labels: app-warden

#9696 Register warden hanz0x07
  _data/handles/hanz0x07.json
Labels: app-warden

#9698 Register warden MrPotatoMagic
  _data/handles/MrPotatoMagic.json
Labels: app-warden

#9700 Register warden mustythefirst
  _data/handles/mustythefirst.json
Labels: app-warden

#9701 Register warden _eperezok
  _data/handles/_eperezok.json
  _data/handles/avatars/_eperezok.jpeg
Labels: app-warden

#9699 Register warden HuntingWaka
  _data/handles/HuntingWaka.json
  _data/handles/avatars/HuntingWaka.jpeg
Labels: app-warden

#9704 Register warden saif_atom
  _data/handles/saif_atom.json
Labels: app-warden

#9708 Register warden Pithoriya
  _data/handles/Pithoriya.json
Labels: app-warden

#9707 Register warden Badger
  _data/handles/Badger.json
  _data/handles/avatars/Badger.png
Labels: app-warden

#9706 Register warden 0x3c
  _data/handles/0x3c.json
Labels: app-warden

#9048 Register warden EricWWFCP
  _data/handles/EricWWFCP.json
Labels: app-warden

#9044 Register warden SamurayLeo
  _data/handles/SamurayLeo.json
Labels: app-warden

#8887 Register warden malaro
  _data/handles/malaro.json
Labels: app-warden

#9712 Register warden securenetizen123
  _data/handles/securenetizen123.json
Labels: app-warden

#9689 Register warden Coollaitar
  _data/handles/Coollaitar.json
Labels: app-warden

#9713 Register warden tantv4668
  _data/handles/avatars/tantv4668.jpeg
  _data/handles/tantv4668.json
Labels: app-warden

#9714 Register warden Hako
  _data/handles/Hako.json
Labels: app-warden

#9721 Register warden pb
  _data/handles/pb.json
Labels: app-warden

#9716 Register warden spoofasa
  _data/handles/spoofasa.json
Labels: app-warden

#9723 Register warden n0ct3m
  _data/handles/n0ct3m.json
Labels: app-warden

#9729 Register warden 1ambda
  _data/handles/1ambda.json
  _data/handles/avatars/1ambda.png
Labels: app-warden

#9724 Register warden klkvr
  _data/handles/klkvr.json
Labels: app-warden

#9711 Register warden NG
  _data/handles/NG.json
Labels: app-warden

#9717 Register warden Rohan_vs
  _data/handles/Rohan_vs.json
Labels: app-warden

#9726 Register warden 0xyanc
  _data/handles/0xyanc.json
Labels: app-warden

#9730 Register warden FredBoat
  _data/handles/FredBoat.json
Labels: app-warden

#9732 Register warden dwward3n
  _data/handles/dwward3n.json
Labels: app-warden

#9733 Register warden p1xel
  _data/handles/p1xel.json
Labels: app-warden

#9738 Register warden wiener
  _data/handles/wiener.json
Labels: app-warden

#9734 Register warden tonyxx7
  _data/handles/tonyxx7.json
Labels: app-warden

#9736 Register warden Kizito
  _data/handles/Kizito.json
Labels: app-warden

#9727 Register warden sdn
  _data/handles/sdn.json
Labels: app-warden

#9681 Register warden T3K
  _data/handles/T3K.json
Labels: app-warden

#9741 Register warden dadabit
  _data/handles/dadabit.json
Labels: app-warden

#9747 Register warden Katie
  _data/handles/Katie.json
Labels: app-warden

#9575 Register warden lily_mendz
  _data/handles/avatars/lily_mendz.png
  _data/handles/lily_mendz.json
Labels: app-warden

#9762 Register warden Apeiron
  _data/handles/Apeiron.json
  _data/handles/avatars/Apeiron.png
Labels: app-warden

#9764 Register warden kademlia
  _data/handles/kademlia.json
Labels: app-warden

#9767 Register warden zynner
  _data/handles/zynner.json
Labels: app-warden

#7957 Register warden mser
  _data/handles/mser.json
Labels: app-warden

#9731 Register warden PaulBirnbaum
  _data/handles/PaulBirnbaum.json
Labels: app-warden

#9776 Register warden aaron
  _data/handles/aaron.json
  _data/handles/avatars/aaron.jpeg
Labels: app-warden

#9742 Register warden jdk
  _data/handles/jdk.json
Labels: app-warden

#9133 Register warden niki
  _data/handles/niki.json
Labels: app-warden

#9683 Register warden SpeedyTurtleTech
  _data/handles/SpeedyTurtleTech.json
Labels: app-warden

#9757 Register warden max10afternoon
  _data/handles/max10afternoon.json
Labels: app-warden

#9777 Register warden rapha
  _data/handles/rapha.json
Labels: app-warden

#9770 Register warden stephan
  _data/handles/stephan.json
Labels: app-warden

#9786 Register warden Cayo
  _data/handles/Cayo.json
Labels: app-warden

#9795 Register warden phillmenezes
  _data/handles/phillmenezes.json
Labels: app-warden

#9790 Register warden salutemada
  _data/handles/salutemada.json
Labels: app-warden

#9797 Register warden semangatmenguli
  _data/handles/semangatmenguli.json
Labels: app-warden

#9772 Register warden sandamalgamage
  _data/handles/avatars/sandamalgamage.jpeg
  _data/handles/sandamalgamage.json
Labels: app-warden

#9753 Register warden AmariS1
  _data/handles/AmariS1.json
  _data/handles/avatars/AmariS1.png
Labels: app-warden

#9768 Register warden v1pachi7
  _data/handles/v1pachi7.json
Labels: app-warden

#9781 Register warden 0x35abir
  _data/handles/0x35abir.json
Labels: app-warden

#9803 Register warden Canyon
  _data/handles/Canyon.json
Labels: app-warden

#9657 Register warden mrLetum
  _data/handles/avatars/mrLetum.jpeg
  _data/handles/mrLetum.json
Labels: app-warden

#9801 Register warden StaubRacing
  _data/handles/StaubRacing.json
Labels: app-warden

#9805 Register warden Krusher
  _data/handles/Krusher.json
Labels: app-warden

#9806 Register warden JimmyK
  _data/handles/JimmyK.json
Labels: app-warden

#9660 Register warden jefestar
  _data/handles/jefestar.json
Labels: app-warden

#9659 Register warden h4cr3
  _data/handles/avatars/h4cr3.jpeg
  _data/handles/h4cr3.json
Labels: app-warden

#9815 Register warden BoltzmannBrain
  _data/handles/BoltzmannBrain.json
  _data/handles/avatars/BoltzmannBrain.jpeg
Labels: app-warden

#9802 Register warden akliuiko
  _data/handles/akliuiko.json
Labels: app-warden

#9821 Register warden Thebest4fun
  _data/handles/Thebest4fun.json
Labels: app-warden

#9823 Register warden cholakov
  _data/handles/cholakov.json
Labels: app-warden

#9794 Register warden markcancode3000
  _data/handles/markcancode3000.json
Labels: app-warden

#9839 Register warden 0xweb3boy
  _data/handles/0xweb3boy.json
Labels: app-warden

#9829 Register warden auditsea
  _data/handles/auditsea.json
  _data/handles/avatars/auditsea.jpeg
Labels: app-warden

#9831 Register warden Wiese39
  _data/handles/Wiese39.json
Labels: app-warden

#9833 Register warden LiRiu
  _data/handles/LiRiu.json
  _data/handles/avatars/LiRiu.png
Labels: app-warden

#9834 Register warden aakansha
  _data/handles/aakansha.json
Labels: app-warden

#9835 Register warden andreaspz
  _data/handles/andreaspz.json
Labels: app-warden

#9812 Register warden sweti-yeti
  _data/handles/sweti-yeti.json
Labels: app-warden

#9840 Register warden abc_hack0r_xyz
  _data/handles/abc_hack0r_xyz.json
Labels: app-warden

#9841 Register warden rodrigof1307
  _data/handles/avatars/rodrigof1307.jpeg
  _data/handles/rodrigof1307.json
Labels: app-warden

#8062 Register warden kim
  _data/handles/kim.json
Labels: app-warden
